services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_MEDIA_HOST: ${NEXT_PUBLIC_MEDIA_HOST}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        NEXT_PUBLIC_ENABLE_BORDER_RADIUS: ${NEXT_PUBLIC_ENABLE_BORDER_RADIUS:-false}
        NEXT_PUBLIC_BORDER_RADIUS: ${NEXT_PUBLIC_BORDER_RADIUS:-m}
    expose:
      - "3000"
    environment:
      API_BASE_URL: ${API_BASE_URL}
      USE_MOCK_DATA: ${USE_MOCK_DATA:-false}
    restart: unless-stopped
