import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import {
	getMessages,
	getTranslations,
	setRequestLocale,
} from "next-intl/server";
import { AudioPlayerBar } from "@/components/audio/audio-player-bar";
import { AudioPlayerProvider } from "@/components/audio/audio-player-context";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { RouteProgress } from "@/components/layout/route-progress";
import { NativeScroll } from "@/components/providers/native-scroll";
import { routing } from "@/i18n/routing";
import { getSiteSettings } from "@/lib/api/site-settings";
import { assertServerEnv } from "@/lib/env";
import { archivo, clashDisplay, vazirmatn } from "@/lib/fonts";
import { buildSiteFontCss } from "@/lib/site-font";
import { buildSiteColorCss, buildSiteSizeCss } from "@/lib/site-theme";
import { getBorderRadiusHtmlAttrs } from "@/lib/theme/border-radius";
import { cn } from "@/lib/utils";
import "../globals.css";

type Props = {
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
};

export function generateStaticParams() {
	return routing.locales.map((locale) => ({ locale }));
}

// Renders hit the CMS live (no-store policy), so a slow backend burns real
// render time. 60s is the Hobby ceiling — it covers the worst-case chain of
// timeout+retry upstream calls (~48s) without letting a hung fetch get the
// function killed at the 15s default.
export const maxDuration = 60;

export async function generateMetadata({
	params,
}: {
	params: Promise<{ locale: string }>;
}): Promise<Metadata> {
	const { locale } = await params;
	const t = await getTranslations({ locale, namespace: "Nav" });
	const siteName = t("brandAlt");
	const siteUrl = process.env.NEXT_PUBLIC_SITE_URL;

	return {
		metadataBase: siteUrl ? new URL(siteUrl) : undefined,
		// `default` guarantees every route has a <title> even mid-stream; pages
		// add their own title which flows through `template`.
		title: {
			default: siteName,
			template: `%s · ${siteName}`,
		},
		description: t("aboutDescription"),
		openGraph: {
			siteName,
			locale,
			type: "website",
		},
		// Next fills in `images` from src/app/opengraph-image.tsx; declaring the
		// card type is what makes X/Twitter render the large preview.
		twitter: {
			card: "summary_large_image",
			title: siteName,
			description: t("aboutDescription"),
		},
	};
}

function getDir(locale: string): "ltr" | "rtl" {
	return locale === "ckb" ? "rtl" : "ltr";
}

/**
 * Injects the dashboard-picked theme (typefaces + surface colors). The CSS is
 * generated by buildSiteFontCss/buildSiteColorCss from fixed family names,
 * sanitized hex values and encodeURIComponent'd, host-allowlisted URLs — no
 * admin-typed string reaches the stylesheet raw.
 */
function SiteFontStyle({ css }: { css: string }) {
	// biome-ignore lint/security/noDangerouslySetInnerHtml: input is the sanitized CSS from buildSiteFontCss, never raw settings data.
	return <style dangerouslySetInnerHTML={{ __html: css }} />;
}

export default async function LocaleLayout({ children, params }: Props) {
	// Fails the request loudly in production when required deploy config is
	// missing, instead of silently rendering an empty site.
	assertServerEnv();

	const { locale } = await params;

	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}

	setRequestLocale(locale);

	// Settings are tag-cached — header/footer read the same row for the logo
	// and donate band, so this fetch is deduplicated rather than doubled.
	const [messages, siteSettings] = await Promise.all([
		getMessages(),
		getSiteSettings(),
	]);
	const isLatin = locale === "ku";
	// One injected sheet: dashboard-picked typefaces + surface colors, both
	// derived from the same cached site-settings row.
	const siteThemeCss = [
		buildSiteFontCss(siteSettings),
		buildSiteColorCss(siteSettings),
		buildSiteSizeCss(siteSettings),
	]
		.filter(Boolean)
		.join("\n");

	return (
		<html
			lang={locale}
			dir={getDir(locale)}
			data-script={isLatin ? "latin" : "arabic"}
			{...getBorderRadiusHtmlAttrs()}
			// Vazirmatn ships on BOTH locales: the header wordmark always renders
			// the Sorani institute name, and Archivo/Clash carry no Arabic glyphs,
			// so ku would otherwise fall back to a random system Arabic face.
			className={cn(
				vazirmatn.variable,
				isLatin && `${archivo.variable} ${clashDisplay.variable}`,
			)}
		>
			{/* `font-sans` resolves through the --font-app-body token (set per
			    script in globals.css) and carries Vazirmatn as the Arabic-glyph
			    fallback behind Archivo. A next/font className here would pin the
			    body to one family with no such chain. */}
			<body className="font-sans antialiased">
				{/* Dashboard-picked typefaces, when configured: @font-face sourced
				    from the same-origin /api/site-font proxy plus --font-app-*
				    overrides. Rendered before the content so the rules apply
				    without a flash of the bundled faces. */}
				{siteThemeCss ? <SiteFontStyle css={siteThemeCss} /> : null}
				<NextIntlClientProvider messages={messages}>
					<NativeScroll>
						<RouteProgress />
						<AudioPlayerProvider>
							<Header />
							{children}
							<Footer />
							<AudioPlayerBar />
						</AudioPlayerProvider>
					</NativeScroll>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
